<?php
/**
 * This file is automatically generated by the wp_install.sh
 *
 * @file Config.php
 */

namespace Base;

class Config {

	public function __construct() {
		// For our purposes, the theme name is the folder name that holds the WP theme.
		$this->theme_name = ( basename( dirname( dirname( __FILE__ ) ) ) );

		// Declare possible variable defaults.
		// just a very basic blog
		$this->has_blog = false;
		// ie ping back, track backs, etc.
		$this->has_full_blog = false;
		// blog comments
		$this->has_comments = false;
		$this->has_ecommerce = false;
		$this->has_news_feed = false;
		$this->has_search = true;
		$this->has_image_slider = true;
		$this->is_template_debug = true;
		$this->has_api = false;
		// FIXME not working: can rename,eg posts_name = 'Latest News'
		$this->posts_name = 'Blog Posts';
		// give editors access to menus
		$this->editor_menus = false;
		// these are all used by Organization schema
		$this->client_name = 'dbsinteractive';
		$this->client_phone = '866-562-7895';	// needs to be 000-000-0000 format
		$this->canonical_url = 'https://www.dbswebsite.com/';
		// custom login url
		$this->login_url = '/dbs-login/';

		$this->has_search=true;
		$this->has_ecommerce=false;
		$this->has_blog=false;
		$this->has_full_blog=false;
		$this->has_comments=false;
		$this->has_news_feed=false;
		$this->has_api='false';
		$this->client_name='kaoprint';
		$this->client_phone='null';
		$this->canonical_url='https://.www.kaoprint.com';
		$this->login_url='/kao-print-login/';
		$this->posts_name='News';
		$this->has_search=false;
		$this->has_ecommerce=false;
		$this->has_blog=false;
		$this->has_full_blog=false;
		$this->has_comments=false;
		$this->has_news_feed=false;
		$this->has_api='false';
		$this->client_name='dbsclients';
		$this->client_phone='null';
		$this->canonical_url='https://.www.dbsclients.com';
		$this->login_url='/dbs-login/';
		$this->posts_name='Blog Posts';
	}
}
