<?php
/**
 * Theme.php
 *
 * Slate base functionality.
 *
 * TODO: This code should NOT be changed on a per project basis. Use Slate.php for that.
 */

namespace Base;

use Base\Admin;
use Base\ThemeView;
use Base\CustomPostType;
use Base\Utilities;
use Base\Config;

global $utils;

class Theme {
	public $theme_name = 'slate';

	public function __construct() {

		$this->css_unique_hash = '';
		$this->js_unique_hash = '';

		// Read the css.hash and js.hash files generated by the gulp script.
		// These files are distinct in order to have 2 separate gulp tasks; one
		// for javascript and one for css.
		if ( file_exists( get_stylesheet_directory() . '/library/css/css.hash' ) ) {
			$this->css_unique_hash = '-' . file_get_contents( get_stylesheet_directory() . '/library/css/css.hash' );
		}

		if ( file_exists( get_stylesheet_directory() . '/library/js/js.hash' ) ) {
			$this->js_unique_hash = '-' . file_get_contents( get_stylesheet_directory() . '/library/js/js.hash' );
		}

		if ( APP_MODE === STAGING || APP_MODE === PRODUCTION ) {
			$this->css_file_extension = $this->css_unique_hash . '.min.css';
		} else {
			$this->css_file_extension = '.css';
		}


		$admin = new Admin;

		// Theme setup calls
		$this->theme_setup();

		// Register Custom Post Types
		$this->registerCustomPostTypes();

		// WP Filters
		$this->filters();
		$this->actions();
	}

	private function actions() {
		add_action( 'init', array( $this, 'base_cleanup' ), 9999 );
		add_action( 'init' , array( $this, 'add_tags_to_attachments' ) );
		add_action( 'init' , array( $this, 'add_custom_image_sizes' ) );
		add_action( 'wp_enqueue_scripts',  array( $this, 'base_enqueue_styles' ) );
		add_action( 'wp_enqueue_scripts',  array( $this, 'base_enqueue_scripts' ) );
		add_action( 'wp_enqueue_scripts',  array( $this, 'base_enqueue_scripts' ) );
		add_action( 'wp_enqueue_scripts',  function() { wp_dequeue_style( 'wp-block-library' ); } );
		add_action( 'admin_head', function() {
			// hide stuff from editors.
			if ( current_user_can( 'wpseo_manager' ) || current_user_can( 'editor' ) ) {
				remove_submenu_page( 'themes.php', 'themes.php' ); // hide the theme selection submenu
				remove_submenu_page( 'themes.php', 'widgets.php' ); // hide the widgets submenu
				remove_submenu_page( 'themes.php', 'customize.php?return=%2Fwp-admin%2Ftools.php' ); // hide the customizer submenu
				remove_submenu_page( 'themes.php', 'customize.php?return=%2Fwp-admin%2Ftools.php&#038;autofocus%5Bcontrol%5D=background_image' ); // hid
			}
		});
	}

	private function filters() {
		add_filter( 'the_content', array( $this, 'filter_ptags_on_images' ) );
		add_filter( 'the_content', array( $this, 'filter_remove_empty_ptags' ), 99 );
		add_filter( 'excerpt_more', array( $this, 'excerpt_more' ) );
		add_filter( 'image_size_names_choose', array( $this, 'add_custom_image_choose' ) );
		add_filter( 'wp_editor_set_quality', array( $this, 'jpeg_custom_quality' ) );
		add_filter( 'clean_url', array( $this, 'async_defer_js' ), 11, 1 );
		add_filter( 'style_loader_src', array( $this, 'remove_query_strs' ), 10, 2 );
		add_filter( 'script_loader_src', array( $this, 'remove_query_strs' ), 10, 2 );

		add_filter( 'mce_buttons_2', array( $this, 'add_tiny_mce_buttons' ), 10, 2 );
		add_filter( 'tiny_mce_before_init', array( $this, 'insert_button_styles' ), 10, 2 );

		add_filter( 'xmlrpc_enabled', '__return_false');
		add_filter( 'pings_open', '__return_false', PHP_INT_MAX);

		add_filter( 'gform_ajax_spinner_url', array( $this, 'replace_loader_spinner' ), 10, 2 );
		/**
		 *  2019-01-29 HB, allows gforms to work with jquery loaded async.
		 *
		 *  The 2 cdata filters wrap the inline gform js in a ready event.
		 *  The confirmation filter handles the post submission page handling,
		 *  aka thank you page, which needs TLC as well. Also, note that ajaxed
		 *  GF forms, have different return values for $confirmation (not well documented).
		 */
		add_filter( 'gform_cdata_open', array( $this, 'wrap_gform_cdata_open' ) );
		add_filter( 'gform_cdata_close', array( $this, 'wrap_gform_cdata_close' ) );
		add_filter( 'gform_confirmation', function( $confirmation, $form, $entry, $ajax ) {
			if ( isset( $confirmation['redirect'] ) ) :
				// this is only available on non-ajaxed forms ???
				$url = esc_url_raw( $confirmation['redirect'] );
				return '<script>window.location.href="' . $url . '";</script>';
			elseif ( isset( $form['confirmation']['pageId'] ) &&  $form['confirmation']['pageId'] != 0 ) :
				// if confirmation is a "page", which is most common for DBS. 'pageID' should always be available
				// no matter what, but this same code does not work on a non-ajaxed form for some reason. See above.
				return '<script>function gformRedirect(){ window.location.href="/?p=' . $form['confirmation']['pageId'] . '";}</script>';
			endif;

			// default ... (probably a simple message confirmation .... untested)
			return $confirmation;
		}, 10 ,4 );
		add_filter( 'wpseo_metabox_prio', function() {
			return 'low';
		});
	}

	/**
	 * Sets up theme defaults and registers support for various WordPress features.
	 * Runs into the after_setup_theme hook, which runs before the init hook.
	 */
	private function theme_setup() {
		add_theme_support( 'automatic-feed-links' );
		add_theme_support( 'html5' );
		add_theme_support( 'title-tag' );
		add_theme_support( 'post-thumbnails' );
		/**
		 * Adds a set of custom styles to the WYSIWYG editor -- 12.19.16 - JD
		 */
		add_editor_style( get_stylesheet_directory_uri() . '/library/css/editor-style' . $this->css_file_extension );
	}

	/**
	 * Cleans up unwanted head code and removed various features.
	 * Is called in dbs_init ("init");
	 */
	public function base_cleanup() {
		remove_action( 'wp_head', 'rsd_link' );
		remove_action( 'wp_head', 'wlwmanifest_link' );
		remove_action( 'wp_head', 'index_rel_link' );
		remove_action( 'wp_head', 'parent_post_rel_link', 10, 0 );
		remove_action( 'wp_head', 'start_post_rel_link', 10, 0 );
		remove_action( 'wp_head', 'adjacent_posts_rel_link_wp_head', 10, 0 );
		remove_action( 'wp_head', 'wp_generator' );
		remove_action( 'wp_head', 'print_emoji_detection_script', 7 );
		remove_action( 'wp_print_styles', 'print_emoji_styles' );
		remove_action( 'rest_api_init', 'wp_oembed_register_route' );
		remove_filter( 'oembed_dataparse', 'wp_filter_oembed_result', 10 );
		remove_action( 'wp_head', 'wp_oembed_add_discovery_links' );
		remove_action( 'wp_head', 'wp_oembed_add_host_js' );
		remove_action( 'wp_head', 'feed_links', 2 );
		remove_action( 'wp_head', 'feed_links_extra', 3 );
		remove_action( 'wp_head', 'wlwmanifest_link' );
		remove_action( 'wp_head', 'rest_output_link_wp_head', 10 );
		add_filter( 'embed_oembed_discover', '__return_false' );
		remove_filter( 'oembed_dataparse', 'wp_filter_oembed_result', 10 );
		remove_action( 'wp_head', 'wp_oembed_add_discovery_links' );
		remove_action( 'wp_head', 'wp_oembed_add_host_js' );
		// Disable REST API link in HTTP headers
		remove_action('template_redirect', 'rest_output_link_header', 11, 0);
		add_filter( 'rest_enabled', '__return_false' );
		add_filter( 'rest_jsonp_enabled', '__return_false' );
		// disable tags.
		unregister_taxonomy_for_object_type( 'post_tag', 'post' );
		// remove_post_type_support('post','thumbnail');
		remove_post_type_support('post','comments');
	}


	public function base_enqueue_styles() {
		global $utils;
		
		wp_register_style( 'base-styles', get_stylesheet_directory_uri() . '/library/css/style-base' . $this->css_unique_hash . '.min.css', null, '1.0' );
		wp_register_style( 'main-styles', get_stylesheet_directory_uri() . '/library/css/style' . $this->css_unique_hash . '.min.css', null, '1.0' );
		wp_register_style( 'front-page-styles', get_stylesheet_directory_uri() . '/library/css/style-front-page' . $this->css_unique_hash . '.min.css', null, '1.0' );
		wp_register_style( 'blog-styles', CDN_TEMPLATE_URL . '/library/css/style-blog' . $this->css_unique_hash . '.min.css', null, '1.0' );
		wp_register_style( 'amp-styles', CDN_TEMPLATE_URL . '/library/css/style-amp' . $this->css_unique_hash . '.min.css', null, '1.0' );

		wp_dequeue_style( 'wp-block-library' );

		if ( $utils->is_amp() ) : // Load amp-specific styling, with the goal of keeping the minified css weight below 50kb.
			wp_enqueue_style( 'amp-styles' );
		elseif ( is_front_page() ):
			wp_enqueue_style( 'front-page-styles' );
		elseif ( is_home() || is_single() || is_archive() || is_search() ) :
			wp_enqueue_style( 'blog-styles' );
		else :
			wp_enqueue_style( 'main-styles' );
		endif; 
		
		if ( ! $utils->is_amp() ) {wp_enqueue_style( 'base-styles' );}

		if ( ! IS_LIVE ) {
			wp_enqueue_style( 'debug-styles', get_stylesheet_directory_uri() . '/library/css/debug' . $this->css_file_extension, null, '1.0' );
		}
	}

	public function base_enqueue_scripts() {
		// Enqueue Arguments:
		// wp_enqueue_script ( <handle>, <src>, <dependencies>, <version>, < in footer? > )
		wp_deregister_script( 'jquery' );
		wp_deregister_script( 'hoverintent-js' );
		/* to load jquery async, see dbswebsite.com Theme.php. Problematic are inline scripts using jquery. These should be in a load event.  */
		wp_register_script( 'jquery', 'https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js#async', '3.5.1' );  // TESTING! 2019-01-25
		wp_enqueue_script( 'jquery' );
		wp_register_script( 'lazyload', get_stylesheet_directory_uri() . '/library/js/vendors/lazyload/dbs-lazyload.js#async', array(), '1.0.0', true );
		wp_enqueue_script( 'lazyload' );
		wp_register_script( 'lightbox', get_stylesheet_directory_uri() . '/library/js/vendors/lightbox/lightbox' . $this->js_unique_hash . '.min.js', array(), null, true );
		wp_enqueue_script( 'globaljs', get_stylesheet_directory_uri() . '/library/js/global' . $this->js_unique_hash . '.min.js#async', array(), '1.0.0', true );
		wp_register_script( 'flickity', get_stylesheet_directory_uri() . '/library/js/vendors/flickity/flickity.pkgd' . $this->js_unique_hash . '.min.js', array(), '2.2.1', true );

		if ( ! IS_LIVE  && ! strstr( $_SERVER['HTTP_HOST'],'staging' ) ) {
			// wp_enqueue_script( 'inspector', 'http://cdnjs.cloudflare.com/ajax/libs/html-inspector/0.8.2/html-inspector.js', array(), null, true );
			wp_enqueue_script( 'inspector', get_stylesheet_directory_uri() . '/library/js/vendors/html-inspector/html-inspector' . $this->js_unique_hash . '.min.js', array(), null, true );
			wp_enqueue_script( 'debug', get_stylesheet_directory_uri() . '/library/js/vendors/debug/debug' . $this->js_unique_hash . '.min.js', array(), null, true );
		}
	}

	/**
	 * Set JPG quality.
	 * For WP >= 3.5
	 *
	 * @since 1.0
	 * @param  [int] $quality An int representation of the quality.
	 * @return [int]
	 */
	public function jpeg_custom_quality( $quality ) {
		return 70;
	}

	/**
	 * Helper functions for async_defer_js()
	 *
	 * @param string $url The URL string.
	 */
	private function set_async( $url ) {
		return $this->dbs_make_cdn( str_replace( '?#async', '', $url ) ). "' async='async";
	}
	private function set_defer( $url ) {
		return $this->dbs_make_cdn( str_replace( '?#defer', '', $url ) ) . "' defer='defer";
	}

	/**
	 * Force defer or async of js.
	 * Just add a #async or #defer to the script in the enqueue to use.
	 * If you are utilizing a plugin and you want to defer or async their script
	 * add it as a case in the correct place. ( SEE tribe-events ).
	 *
	 * @param  string $url The included URL string.
	 * @return [string]
	 */
	public function async_defer_js( $url ) {
		global $dbs;
		switch ( $url ) :
			case ( is_admin() ): // DONT SET ASYNC OR DEFER
			case ( $_SERVER['REQUEST_URI'] === $dbs->login_url ) :
			case ( $_SERVER['REQUEST_URI'] === '/wp-admin/' ) :
			case ( false === strpos( $url, '.js' ) ):
				return $url;
				break;
			case ( false !== strpos( $url, '#async' ) ): // SET ASYNC
				return $this->set_async( $url );
				break;
			case ( false !== strpos( $url, '#defer' ) ): // SET DEFER
			case ( false !== strpos( $url, 'tribe-events' ) ):
				return $this->set_defer( $url );
				break;
			case ( strpos( $url, '/plugins/' ) > 0 ):
				return $this->set_defer( $url );
			case ( strpos( $url, '/vendors/' ) > 0 ):
				return $this->set_defer( $url );
			case ( strpos( $url, '/wp-includes/' ) > 0 ):
				return $this->set_defer( $url );
			default:
				return $url;
		endswitch;
	}

	/**
	 * Removes annoying [...] to a Read More Link.
	 * Default Excerpt - Customization
	 * Removes annoying [...] appended to the end of an excerpt
	 *
	 * @return [string] Read more.. link
	 * @return string '...'
	 */
	public function excerpt_more( $more ) {
		global $post, $dbs;
		// edit here if you like
		return '...<br><br><a class="excerpt-read-more button" href="'. get_permalink( $post->ID ) . '" title="'. __( 'Read', $dbs->theme_name ) . esc_attr( get_the_title( $post->ID ) ) . '"></a>';
	}
	
 	/**
	 * Custom Excerpt
	 *
	 * Use this function to create a custom length excerpt with an optional button
	 *
	 * To display: $theme->custom_excerpt(excerpt_word_count, true, button-class);
	 *	Example: $theme->custom_excerpt(25, true, 'button--inline');
	 *
	 * If no argumenta are passed, the excerpt will return with the default values (with no button)
	 *
	 *		$theme->custom_excerpt(); // Valid
	 *
	 * @param int $length = Excerpt length in words
	 * @param bool $button = if false return raw WP excerpt as text; if true add a button like link
	 * @param string $read_more_type = 'button-class'
	 *
	 * @return string Customized Excerpt and Read More link
	 */
 	function custom_excerpt( int $length = 55, $button = false, string $read_more_type = 'button' ) {
 		// Trim to length specified by $length
		$excerpt = wp_trim_words( get_the_excerpt(), $length );
		// if no excerpt, lets check for a yoast seo meta description and use that.
		if ( empty( $excerpt ) ) {
			global $post; 
			$excerpt = get_post_meta( $post->ID, '_yoast_wpseo_metadesc', true ); 
		}
		// Returns the excerpt at whatever length set, appends the ellipses, and sets the default or specified button class to the read more link.
		if ( $button ) {
			return '<div class="excerpt-content">' . $excerpt . '</div><a class="' . $read_more_type . ' excerpt-read-more" href="'. get_permalink( $post->ID ) . '" title="'. 'Read' . esc_attr( get_the_title( $post->ID ) ) . '">'. 'Read more' .'</a>';
		} else {
			// raw with ellipsis removed, add it manually if you want it.
			return str_replace('&hellip;', '', $excerpt );
		} 
	}

	/**
	 * Removes query strings from js / css, which aren't cached in some situations.
	 *
	 * @return $string
	 */
	public function remove_query_strs( $src ) {
		if ( strpos( $src, '?ver=' ) ) {
			$src = remove_query_arg( 'ver', $src );
		}
		return $src;
	}

	function add_tags_to_attachments() {
		register_taxonomy_for_object_type( 'post_tag', 'attachment' );
	}

	/**
	 * Adds custom image sizes.
	 *
	 * @author Michael Large DBS Interactive
	 * Update here. As of WP 4.4 the default WordPress image sizes are as follows:
	 * https://developer.wordpress.org/reference/functions/the_post_thumbnail/
	 *
	 * the_post_thumbnail( 'thumbnail' ); // Thumbnail (150 x 150 hard cropped)
	 * the_post_thumbnail( 'medium' ); // Medium resolution (300 x 300 max height 300px)
	 * the_post_thumbnail( 'medium_large' ); // Medium Large (added in WP 4.4) resolution (768 x 0 infinite height)
	 * the_post_thumbnail( 'large' ); // Large resolution (1024 x 1024 max height 1024px)
	 * the_post_thumbnail( 'extra_large' ); // Extra Large resolution (1300px width)
	 * the_post_thumbnail( 'huge' ); // Huge resolution (2000px width)
	 * the_post_thumbnail( 'full' ); // Full resolution (original size uploaded)
	 *
	 * There was discussion for an 'extra_large' : 1300px and a 'huge' : 2000px size.
	 * https://github.com/DBSInteractive/dbsinteractive-slate/issues/1
	 * Below are added custom image sizes for DBS>Interactive Dev use:
	 */
	public function add_custom_image_sizes() {
		add_image_size( 'extra_large', 1300, 0 );
		add_image_size( 'huge', 2000, 0 );
	}

	/**
	 * Adds custom sizes to Media admin area so that you can choose the custom sizes.
	 */
	public function add_custom_image_choose( $sizes ) {
		return array_merge( $sizes, array(
			'full-page-featured' => __( 'Full Page Featured Image' ),
		));
	}

	/**
	 * View
	 *
	 * An alternative to the native WP function `get_template_part`
	 *
	 * @see PHP class ThemeView
	 * @param string $file The file path, relative to theme root
	 * @param array  $args The arguments to pass to this file. Optional.
	 *  Default empty array.
	 *
	 * @return string The HTML from $file
	 */
	public static function view( $file, $args = array() ) {
		$template = new ThemeView( $file, $args );
		$template->render();
	}

	/**
	 * Remove the <p></p> from around <img> tags.
	 * Runs on the_content filter
	 *
	 * @link http://css-tricks.com/snippets/wordpress/remove-paragraph-tags-from-around-images/
	 */
	public function filter_ptags_on_images( $content ) {
		return preg_replace( '/<p>\s*(<a .*>)?\s*(<img .*>)\s*(<\/a>)?\s*<\/p>/iU', '\1\2\3', $content );
	}

	/**
	 * Remove empty <p></p> tags.
	 * Runs on the_content filter
	 */
	public function filter_remove_empty_ptags( $content ) {
		return preg_replace( '/<p>\s*<\/p>/iU', '', $content );
	}

	/**
	 * Replaces the gravity forms loader spinner with a 1x1 transparent gif.
	 * Requires you to style the spinner manually.
	 */
	public function replace_loader_spinner( $_, $__ ) {
		return 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7';
	}

	/**
	 * TODO: Document how this works, or if we even use it. What it is.
	 */
	function slides_add_local_field_groups() {
		register_field_group(array(
			'id' => 'acf_image-slider',
			'title' => 'Image Slider',
			'fields' => array(
			array(
				'key' => 'field_55b7db359ed22',
				'label' => 'Images',
				'name' => 'images',
				'type' => 'repeater',
				'sub_fields' => array(
					array(
						'key' => 'field_55b7db509ed23',
						'label' => 'image',
						'name' => 'image',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array(
						'key' => 'field_55b7db5d9ed24',
						'label' => 'overlay',
						'name' => 'overlay',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
			),
			'location' => array(
			array(
				array(
					'param' => 'page',
					'operator' => '==',
					'value' => '1721',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array(
				array(
					'param' => 'page',
					'operator' => '==',
					'value' => '701',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			),
			'options' => array(
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array(),
			),
			'menu_order' => 0,
		));

		/*
		 WTF is this and why do we need it ? Please document oddball stuff like this.
		acf_add_local_field_group(array(
			'key' => 'group_1',
			'title' => 'My Group',
			'fields' => array(
			array(
				'key' => 'field_1',
				'label' => 'Sub Title',
				'name' => 'sub_title',
				'type' => 'text',
			),
			),
			'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
			),
		));
		*/
	}

	private function dbs_make_cdn( $url ) {
		return str_replace( WP_SITEURL, DBS_STATIC_URL, $url );
	}

	/* function to return the theme folder uri, substituting the static content url for cdn (if there is one). */
	private function dbs_template_uri() {
		return str_replace( WP_SITEURL, DBS_STATIC_URL, get_stylesheet_directory_uri() );
	}

	/**
	 * Registers all custom post types.
	 */
	public function registerCustomPostTypes() {
		/*
		 TODO: Register any potential custom post types.
		 $testimonial = new CustomPostType(
			array(
				'post_type_name' => 'testimonial',
				'singular' => 'Testimonial',
				'plural' => 'Testimonials',
				'slug' => 'testimonial'
			),
			array(
				'supports' => array( 'title', 'editor' ),
			)
		);
		 */
	}


	// Note: custom search improvements are obsolted by use of the plugin we now use 2017-09-15


	/**
	 * Callback function to insert 'styleselect' into the $buttons array
	 */
	function add_tiny_mce_buttons( $buttons ) {
		array_unshift( $buttons, 'styleselect' );
		return $buttons;
	}

	/**
	 * Callback function to filter the MCE settings
	 */
	function insert_button_styles( $init_array ) {
		// Define the style_formats array
		$style_formats = array(
			// Each array child is a format with it's own settings
			array(
				'title'		=>	'Flat Button',
				'selector'	=>	'a',
				'classes'	=>	'button button-flat',
				'role'		=>	'button',
			),
			array(
				'title'		=>	'Gradient Button',
				'selector'	=>	'a',
				'classes'	=>	'button button-grident',
				'role'		=>	'button',
			),
			array(
				'title'		=>	'Ghost Button',
				'selector'	=>	'a',
				'classes'	=>	'button button-ghost',
				'role'		=>	'button',
			),
			array(
				'title'		=>	'Pill Button',
				'selector'	=>	'a',
				'classes'	=>	'button button-pill',
				'role'		=>	'button',
			),
			array(
				'title'		=>	'Pill Ghost Button',
				'selector'	=>	'a',
				'classes'	=>	'button button-pill-ghost',
				'role'		=>	'button',
			),

		);
		// Insert the array, JSON ENCODED, into 'style_formats'
		$init_array['style_formats'] = json_encode( $style_formats );
		return $init_array;
	}

	/**
	* These 2 filters put GF inline scripts in a ready event, solving some intermittent js errors,
	* and allow gforms to work with jquery loaded async. 2019-01-22 HB
	*/
	public function wrap_gform_cdata_open( $content = '' ) {
		$content = 'document.addEventListener( "DOMContentLoaded", function() { ';
		return $content;
	}
	public function wrap_gform_cdata_close( $content = '' ) {
		$content = ' }, false );';
		return $content;
	}
}
